'use client';
import './globals.css';
import { Inter } from 'next/font/google';
import { useState } from 'react';
import CartContext from './_context/CartContext';

import { ClerkProvider } from '@clerk/nextjs';

import Header from './_component/Header';
import Footer from './_component/Footer';


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  const [cart, setCart] = useState([]);

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <CartContext.Provider value={{ cart, setCart }}>
            <Header />
              {children}
            <Footer />
          </CartContext.Provider>
        </body>
      </html>
    </ClerkProvider>
  )
}
